package com.missa.b360.core.domain.model

import com.missa.b360.R

/**
 * Catalogue traduit des fonctionnalites detaillees des modules.
 *
 * [ModuleSousElements] conserve les libelles techniques (francais) qui servent
 * de cles dans la configuration des profils ; cet objet leur associe la chaine
 * traduite affichee a l'utilisateur (fr, en, es, ar, zh).
 */
object ModuleFonctions {

    private val libelles: Map<String, Int> = mapOf(
        "Fournisseurs" to R.string.fonc_fournisseurs,
        "Demandes d'achat" to R.string.fonc_demandes_d_achat,
        "Appels d'offres" to R.string.fonc_appels_d_offres,
        "Commandes fournisseurs" to R.string.fonc_commandes_fournisseurs,
        "Réceptions" to R.string.fonc_receptions,
        "Contrôle qualité entrée" to R.string.fonc_controle_qualite_entree,
        "Factures fournisseurs" to R.string.fonc_factures_fournisseurs,
        "Avoirs fournisseurs" to R.string.fonc_avoirs_fournisseurs,
        "Contrats fournisseurs" to R.string.fonc_contrats_fournisseurs,
        "Évaluations fournisseurs" to R.string.fonc_evaluations_fournisseurs,
        "Clients" to R.string.fonc_clients,
        "Prospects" to R.string.fonc_prospects,
        "Devis" to R.string.fonc_devis,
        "Commandes clients" to R.string.fonc_commandes_clients,
        "Livraisons" to R.string.fonc_livraisons,
        "Factures clients" to R.string.fonc_factures_clients,
        "Avoirs clients" to R.string.fonc_avoirs_clients,
        "Retours clients" to R.string.fonc_retours_clients,
        "Relances clients" to R.string.fonc_relances_clients,
        "Contrats clients" to R.string.fonc_contrats_clients,
        "Conditions de paiement" to R.string.fonc_conditions_de_paiement,
        "Articles" to R.string.fonc_articles,
        "Catégories d'articles" to R.string.fonc_categories_d_articles,
        "Entrepôts" to R.string.fonc_entrepots,
        "Mouvements de stock" to R.string.fonc_mouvements_de_stock,
        "Entrées" to R.string.fonc_entrees,
        "Sorties" to R.string.fonc_sorties,
        "Transferts" to R.string.fonc_transferts,
        "Inventaires" to R.string.fonc_inventaires,
        "Réservations de stock" to R.string.fonc_reservations_de_stock,
        "Seuils d'alerte" to R.string.fonc_seuils_d_alerte,
        "Valorisation de stock" to R.string.fonc_valorisation_de_stock,
        "Lots / Séries" to R.string.fonc_lots_series,
        "Nomenclatures" to R.string.fonc_nomenclatures,
        "Gammes de fabrication" to R.string.fonc_gammes_de_fabrication,
        "Ordres de fabrication" to R.string.fonc_ordres_de_fabrication,
        "Planning de production" to R.string.fonc_planning_de_production,
        "Lancements" to R.string.fonc_lancements,
        "Consommations matières" to R.string.fonc_consommations_matieres,
        "Déclarations de production" to R.string.fonc_declarations_de_production,
        "Produits finis" to R.string.fonc_produits_finis,
        "Sous-traitance" to R.string.fonc_sous_traitance,
        "Coûts de production" to R.string.fonc_couts_de_production,
        "Catalogue de prestations" to R.string.fonc_catalogue_de_prestations,
        "Contrats de service" to R.string.fonc_contrats_de_service,
        "Demandes d'intervention" to R.string.fonc_demandes_d_intervention,
        "Planning des interventions" to R.string.fonc_planning_des_interventions,
        "Interventions" to R.string.fonc_interventions,
        "Comptes-rendus d'intervention" to R.string.fonc_comptes_rendus_d_intervention,
        "Tickets / SAV" to R.string.fonc_tickets_sav,
        "Garanties" to R.string.fonc_garanties,
        "Facturation des prestations" to R.string.fonc_facturation_des_prestations,
        "Projets" to R.string.fonc_projets,
        "Phases" to R.string.fonc_phases,
        "Tâches" to R.string.fonc_taches,
        "Planning projet" to R.string.fonc_planning_projet,
        "Affectation des ressources" to R.string.fonc_affectation_des_ressources,
        "Budgets projet" to R.string.fonc_budgets_projet,
        "Suivi des temps" to R.string.fonc_suivi_des_temps,
        "Suivi d'avancement" to R.string.fonc_suivi_d_avancement,
        "Documents projet" to R.string.fonc_documents_projet,
        "Rentabilité projet" to R.string.fonc_rentabilite_projet,
        "Employés" to R.string.fonc_employes,
        "Contrats de travail" to R.string.fonc_contrats_de_travail,
        "Postes" to R.string.fonc_postes,
        "Organigramme" to R.string.fonc_organigramme,
        "Congés et absences" to R.string.fonc_conges_et_absences,
        "Notes de frais" to R.string.fonc_notes_de_frais,
        "Paie" to R.string.fonc_paie,
        "Recrutement" to R.string.fonc_recrutement,
        "Formations" to R.string.fonc_formations,
        "Évaluations" to R.string.fonc_evaluations,
        "Compétences" to R.string.fonc_competences,
        "Plan comptable" to R.string.fonc_plan_comptable,
        "Journaux comptables" to R.string.fonc_journaux_comptables,
        "Écritures comptables" to R.string.fonc_ecritures_comptables,
        "Grand livre" to R.string.fonc_grand_livre,
        "Balance" to R.string.fonc_balance,
        "Compte de résultat" to R.string.fonc_compte_de_resultat,
        "Bilan" to R.string.fonc_bilan,
        "TVA" to R.string.fonc_tva,
        "Lettrage" to R.string.fonc_lettrage,
        "Clôture comptable" to R.string.fonc_cloture_comptable,
        "Immobilisations" to R.string.fonc_immobilisations,
        "Comptes bancaires" to R.string.fonc_comptes_bancaires,
        "Règlements clients" to R.string.fonc_reglements_clients,
        "Règlements fournisseurs" to R.string.fonc_reglements_fournisseurs,
        "Échéanciers" to R.string.fonc_echeanciers,
        "Prévisions de trésorerie" to R.string.fonc_previsions_de_tresorerie,
        "Rapprochements bancaires" to R.string.fonc_rapprochements_bancaires,
        "Effets de commerce" to R.string.fonc_effets_de_commerce,
        "Lignes de crédit" to R.string.fonc_lignes_de_credit,
        "Opportunités" to R.string.fonc_opportunites,
        "Pipeline commercial" to R.string.fonc_pipeline_commercial,
        "Activités" to R.string.fonc_activites,
        "Campagnes marketing" to R.string.fonc_campagnes_marketing,
        "Scoring" to R.string.fonc_scoring,
        "Historique relation client" to R.string.fonc_historique_relation_client,
        "Objectifs commerciaux" to R.string.fonc_objectifs_commerciaux,
        "Plans de contrôle" to R.string.fonc_plans_de_controle,
        "Contrôles qualité" to R.string.fonc_controles_qualite,
        "Non-conformités" to R.string.fonc_non_conformites,
        "Actions correctives" to R.string.fonc_actions_correctives,
        "Audits qualité" to R.string.fonc_audits_qualite,
        "Réclamations clients" to R.string.fonc_reclamations_clients,
        "Certifications" to R.string.fonc_certifications,
        "Indicateurs qualité" to R.string.fonc_indicateurs_qualite,
        "Équipements" to R.string.fonc_equipements,
        "Parcs machines" to R.string.fonc_parcs_machines,
        "Interventions de maintenance" to R.string.fonc_interventions_de_maintenance,
        "Maintenance préventive" to R.string.fonc_maintenance_preventive,
        "Maintenance corrective" to R.string.fonc_maintenance_corrective,
        "Planning de maintenance" to R.string.fonc_planning_de_maintenance,
        "Pièces détachées" to R.string.fonc_pieces_detachees,
        "Historique des pannes" to R.string.fonc_historique_des_pannes,
        "Coûts de maintenance" to R.string.fonc_couts_de_maintenance,
        "Expéditions" to R.string.fonc_expeditions,
        "Transporteurs" to R.string.fonc_transporteurs,
        "Bons d'expédition" to R.string.fonc_bons_d_expedition,
        "Tracking" to R.string.fonc_tracking,
        "Emballages" to R.string.fonc_emballages,
        "Coûts logistiques" to R.string.fonc_couts_logistiques,
        "Tournées de livraison" to R.string.fonc_tournees_de_livraison,
        "Preuves de livraison" to R.string.fonc_preuves_de_livraison,
        "Tableaux de bord" to R.string.fonc_tableaux_de_bord,
        "Indicateurs KPI" to R.string.fonc_indicateurs_kpi,
        "Rapports standards" to R.string.fonc_rapports_standards,
        "Rapports personnalisés" to R.string.fonc_rapports_personnalises,
        "Exports" to R.string.fonc_exports,
        "Analyses multicritères" to R.string.fonc_analyses_multicriteres,
        "Alertes" to R.string.fonc_alertes,
    )

    /** Ressource traduite d'une fonctionnalite, ou null si le libelle est inconnu. */
    fun libelleRes(nom: String): Int? = libelles[nom]
}
